[workspace]
members = ["libc-shim","macros"]

[package]
name = "firewall-vis"
version = "0.1.0"
edition = "2024"

[dependencies]
macros = { path = "macros" }
rocket = { version = "0.5.1", features = ["json", "serde_json"] }
serde = { version = "1.0.228", features = ["derive"] }
sea-orm = { version = "1", features = ["sqlx-sqlite", "runtime-tokio-rustls"] }
utoipa = { version = "5.5.0", features = ["rocket_extras"] }
utoipa-scalar = { version = "0.3.0", features = ["rocket"] }
